version: "3.9"

services:
  db:
    image: postgres
    env_file:
      - chat-backend/.env.db
    networks:
      - my_network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - my_network

  app:
    build:
      context: chat-backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - chat-backend/.env
    volumes:
      - ./chat-backend:/code
    depends_on:
      - db
    #      - redis
    networks:
      - my_network

  ws:
    environment:
      - NODE_ENV=development
    build:
      context: ws
      dockerfile: Dockerfile
    container_name: ws
    volumes:
      - ./ws:/ws
    ports:
      - "3000:3000"
      - "9229:9229"
    networks:
      - my_network

  storage:
    build:
      context: storage
      dockerfile: Dockerfile
    container_name: storage
    volumes:
      - storage-data:/usr/src/app/uploads
    ports:
      - "49160:8999"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  storage-data:
