"""empty message

Revision ID: 1fa7b1540298
Revises: fcc860a85bc2
Create Date: 2024-04-04 11:30:35.643542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1fa7b1540298'
down_revision: Union[str, None] = 'fcc860a85bc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seen', sa.Column('chat_id', sa.Integer(), nullable=False))
    op.drop_column('seen', 'time_created')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seen', sa.Column('time_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('seen', 'chat_id')
    # ### end Alembic commands ###
