"""empty message

Revision ID: 4a9b7177f7b8
Revises: e204288d7c31
Create Date: 2024-02-06 23:30:47.792545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a9b7177f7b8'
down_revision: Union[str, None] = 'e204288d7c31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatevent', sa.Column('chat_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'chatevent', 'chats', ['chat_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chatevent', type_='foreignkey')
    op.drop_column('chatevent', 'chat_id')
    # ### end Alembic commands ###
