"""empty message

Revision ID: 66f1ed3841d9
Revises: 4a9b7177f7b8
Create Date: 2024-02-06 23:46:31.793557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66f1ed3841d9'
down_revision: Union[str, None] = '4a9b7177f7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatevent', sa.Column('time_created', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chatevent', 'time_created')
    # ### end Alembic commands ###
