"""empty message

Revision ID: 778f947e11c2
Revises: 7887a5f215c6
Create Date: 2024-03-25 11:25:00.939449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '778f947e11c2'
down_revision: Union[str, None] = '7887a5f215c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatevent', sa.Column('chatevent', sa.String(), nullable=False))
    op.drop_column('chatevent', 'event')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatevent', sa.Column('event', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('chatevent', 'chatevent')
    # ### end Alembic commands ###
