"""empty message

Revision ID: a0f3056824c3
Revises: 1fa7b1540298
Create Date: 2024-04-04 11:31:51.626046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0f3056824c3'
down_revision: Union[str, None] = '1fa7b1540298'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'seen', 'chats', ['chat_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'seen', type_='foreignkey')
    # ### end Alembic commands ###
