"""empty message

Revision ID: a7913ad65f73
Revises: 283be40a7ebd
Create Date: 2024-05-16 13:32:22.320604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7913ad65f73'
down_revision: Union[str, None] = '283be40a7ebd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photos')
    op.alter_column('blocked', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('blocked', 'blocked_user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key(None, 'blocked', 'users', ['blocked_user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'blocked', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('chatevent', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key(None, 'chatevent', 'users', ['second_user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'chatevent', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('files', sa.Column('url', sa.String(), nullable=False))
    op.add_column('files', sa.Column('name', sa.String(), nullable=False))
    op.add_column('files', sa.Column('type', sa.String(), nullable=False))
    op.add_column('files', sa.Column('size', sa.Integer(), nullable=False))
    op.add_column('files', sa.Column('caption', sa.String(), nullable=False))
    op.add_column('files', sa.Column('as_file', sa.Boolean(), nullable=True))
    op.drop_column('files', 'file')
    op.alter_column('folders', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key(None, 'folders', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('reactions', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key(None, 'reactions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('seen', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key(None, 'seen', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'seen', type_='foreignkey')
    op.alter_column('seen', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'reactions', type_='foreignkey')
    op.alter_column('reactions', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'folders', type_='foreignkey')
    op.alter_column('folders', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('files', sa.Column('file', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('files', 'as_file')
    op.drop_column('files', 'caption')
    op.drop_column('files', 'size')
    op.drop_column('files', 'type')
    op.drop_column('files', 'name')
    op.drop_column('files', 'url')
    op.drop_constraint(None, 'chatevent', type_='foreignkey')
    op.drop_constraint(None, 'chatevent', type_='foreignkey')
    op.alter_column('chatevent', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'blocked', type_='foreignkey')
    op.drop_constraint(None, 'blocked', type_='foreignkey')
    op.alter_column('blocked', 'blocked_user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('blocked', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_table('photos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('mes_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('photo', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['mes_id'], ['messages.id'], name='photos_mes_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='photos_pkey')
    )
    # ### end Alembic commands ###
