"""empty message

Revision ID: e0cd3e1e1fe3
Revises: 778f947e11c2
Create Date: 2024-03-25 13:15:36.933338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0cd3e1e1fe3'
down_revision: Union[str, None] = '778f947e11c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chatevent_chat_id_fkey', 'chatevent', type_='foreignkey')
    op.create_foreign_key(None, 'chatevent', 'chats', ['chat_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('chatfolder_chat_id_fkey', 'chatfolder', type_='foreignkey')
    op.drop_constraint('chatfolder_folder_id_fkey', 'chatfolder', type_='foreignkey')
    op.create_foreign_key(None, 'chatfolder', 'chats', ['chat_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'chatfolder', 'folders', ['folder_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('chatproject_chat_id_fkey', 'chatproject', type_='foreignkey')
    op.create_foreign_key(None, 'chatproject', 'chats', ['chat_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('chatuser_chat_id_fkey', 'chatuser', type_='foreignkey')
    op.create_foreign_key(None, 'chatuser', 'chats', ['chat_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('files_mes_id_fkey', 'files', type_='foreignkey')
    op.create_foreign_key(None, 'files', 'messages', ['mes_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('messages_chat_id_fkey', 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'chats', ['chat_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('photos_mes_id_fkey', 'photos', type_='foreignkey')
    op.create_foreign_key(None, 'photos', 'messages', ['mes_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('reactions_mes_id_fkey', 'reactions', type_='foreignkey')
    op.create_foreign_key(None, 'reactions', 'messages', ['mes_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('replies_mes_id_fkey', 'replies', type_='foreignkey')
    op.create_foreign_key(None, 'replies', 'messages', ['mes_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'replies', type_='foreignkey')
    op.create_foreign_key('replies_mes_id_fkey', 'replies', 'messages', ['mes_id'], ['id'])
    op.drop_constraint(None, 'reactions', type_='foreignkey')
    op.create_foreign_key('reactions_mes_id_fkey', 'reactions', 'messages', ['mes_id'], ['id'])
    op.drop_constraint(None, 'photos', type_='foreignkey')
    op.create_foreign_key('photos_mes_id_fkey', 'photos', 'messages', ['mes_id'], ['id'])
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key('messages_chat_id_fkey', 'messages', 'chats', ['chat_id'], ['id'])
    op.drop_constraint(None, 'files', type_='foreignkey')
    op.create_foreign_key('files_mes_id_fkey', 'files', 'messages', ['mes_id'], ['id'])
    op.drop_constraint(None, 'chatuser', type_='foreignkey')
    op.create_foreign_key('chatuser_chat_id_fkey', 'chatuser', 'chats', ['chat_id'], ['id'])
    op.drop_constraint(None, 'chatproject', type_='foreignkey')
    op.create_foreign_key('chatproject_chat_id_fkey', 'chatproject', 'chats', ['chat_id'], ['id'])
    op.drop_constraint(None, 'chatfolder', type_='foreignkey')
    op.drop_constraint(None, 'chatfolder', type_='foreignkey')
    op.create_foreign_key('chatfolder_folder_id_fkey', 'chatfolder', 'folders', ['folder_id'], ['id'])
    op.create_foreign_key('chatfolder_chat_id_fkey', 'chatfolder', 'chats', ['chat_id'], ['id'])
    op.drop_constraint(None, 'chatevent', type_='foreignkey')
    op.create_foreign_key('chatevent_chat_id_fkey', 'chatevent', 'chats', ['chat_id'], ['id'])
    # ### end Alembic commands ###
