"""empty message

Revision ID: fcc860a85bc2
Revises: e0cd3e1e1fe3
Create Date: 2024-03-31 22:46:20.025091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcc860a85bc2'
down_revision: Union[str, None] = 'e0cd3e1e1fe3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('update',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mes_id', sa.String(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('chatevent', sa.String(), nullable=False),
    sa.Column('new_text', sa.String(), nullable=True),
    sa.Column('time_created', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('reactions', sa.Column('time_created', sa.TIMESTAMP(), nullable=True))
    op.add_column('seen', sa.Column('mes_time', sa.TIMESTAMP(), nullable=False))
    op.add_column('seen', sa.Column('time_created', sa.TIMESTAMP(), nullable=True))
    op.drop_constraint('seen_mes_id_fkey', 'seen', type_='foreignkey')
    op.drop_column('seen', 'mes_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seen', sa.Column('mes_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('seen_mes_id_fkey', 'seen', 'messages', ['mes_id'], ['id'])
    op.drop_column('seen', 'time_created')
    op.drop_column('seen', 'mes_time')
    op.drop_column('reactions', 'time_created')
    op.drop_table('update')
    # ### end Alembic commands ###
